### ISSUE TITLE
What if you have multiple cito categories for one ref?

### ISSUE THREAD

**Issue by schymane** [jcheminform/cito-editorial#2]
Hi @egonw this is a really good read and I think clear ... do you have any guidance on how you would like people to deal with the case where you may have multiple cito categories?
For instance, if we build on the MetFrag paper (DOI: [10.1186/s13321-016-0115-9](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-016-0115-9/)) we will have `cito:citesAsDataSource` for the evaluation data and `cito:usesMethodIn` if we use the code ... do you prefer`[cito:citesAsDataSource] [cito:usesMethodIn]` or e.g. `[cito:citesAsDataSource, cito:usesMethodIn]` or similar variant?

**Comment by egonw** [comment]
Yes, this came up in an email discussion too. I want the first option (`[cito:citesAsDataSource] [cito:usesMethodIn]`) and will include this in the write up.

**Comment by schymane** [comment]
Agree with the first option too. Avoids all sorts of potential separator issues ...

**Comment by egonw** [comment]
All this is now addressed in the new Markdown approach. But we have to wait until SpringerNature does something that allows this information to not me lost in the PDF.
